import Head from "next/head";
import styles from "@/modules/index.module.css";
import AdsClickIcon from "@mui/icons-material/AdsClick";
import Cards from "@/componentes/staffCard";
import CardPortfolio from "@/componentes/CardPortfolio";

const services = [
  {
    icon: <AdsClickIcon />,
    title: "Diseño Web",
    description:
      "Creamos sitios web atractivos, funcionales y adaptables a todos los dispositivos, optimizados para ofrecer una experiencia de usuario excelente y lograr tus objetivos en línea.",
  },
  {
    icon: <AdsClickIcon />,
    title: "Marketing Digital",
    description:
      "Desarrollamos estrategias de marketing digital personalizadas para aumentar tu presencia en internet, atraer más clientes y mejorar la conversión a través de SEO, SEM, redes sociales y más.",
  },
  {
    icon: <AdsClickIcon />,
    title: "Optimizacion de equipos",
    description:
      "Mejoramos el rendimiento de tus equipos mediante configuraciones personalizadas y ajustes que garantizan mayor velocidad, eficiencia y vida útil del hardware.",
  },
  {
    icon: <AdsClickIcon />,
    title: "Mantenimiento Preventivo",
    description:
      "Prolonga la vida útil de tus dispositivos con un mantenimiento preventivo regular, asegurando que tus equipos funcionen de manera óptima y evitando fallos inesperados.",
  },
  {
    icon: <AdsClickIcon />,
    title: "Control de Redes y Servidores",
    description:
      "Monitoreamos y gestionamos tus redes y servidores para asegurar un funcionamiento ininterrumpido, garantizando la seguridad y el rendimiento de tu infraestructura tecnológica.",
  },
  {
    icon: <AdsClickIcon />,
    title: "Asistencia 24/7",
    description:
      "Ofrecemos soporte técnico continuo, las 24 horas del día, los 7 días de la semana, para resolver cualquier problema técnico que pueda surgir, manteniendo tu negocio en funcionamiento sin interrupciones.",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Kraken Soluciones</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.heroContainer}></div>
      <div className={styles.container}>
        <div className={styles.aboutContainer}>
          {/* <div>
            <Image
              src={aboutPic}
              width={450}
              height={300}
              alt="Picture of About"
            />
          </div> */}
          <div className={styles.aboutText}>
            <h1 className={styles.title}>Nuestra Filosofía</h1>
            <div className={styles.aboutParagraph}>
            <p>
            Bienvenido a Kraken, donde la tecnología e innovación llevan su negocio al siguiente nivel. Conformado por tres amigos apasionados y expertos en sus áreas, destacamos por nuestro enfoque integral y compromiso con la satisfacción del cliente.
            </p>
            <p>
            Desde nuestro inicio, nos dedicamos a anticipar y resolver problemas informáticos, permitiendo a empresas y emprendedores destacarse en el mundo virtual.

            </p>
            <p>
            Nuestro equipo incluye un fullstack developer especializado en soluciones digitales innovadoras, un estratega de marketing con visión creativa y estratégica, y un especialista en servidores y seguridad web para garantizar la protección de sus datos.

            </p>
            <p>
            En Kraken, forjamos asociaciones basadas en la confianza y el compromiso con la excelencia. Sea nuestro socio tecnológico confiable mientras navega por el mundo digital. Juntos, hagamos realidad su visión.

            </p>
            <p>
            Descubra cómo transformar su negocio hoy con Kraken.

            </p>
            </div>
          </div>
        </div>
      </div>
      <div className={styles.container}>
      <div className={styles.serviceContainer}> 
        <div className={styles.servicesTitle}>
          <h1  className={styles.servicesTitle}>Nuestros Servicios</h1>
          <h3>
          Podemos brindarle una solución integral de mantenimiento a través de planes de abonos personalizados.
          </h3>
        </div>
        <div className={styles.servicesCardContainer}>
            {
              services.map( e => <CardPortfolio key={e.title} title={e.title} detail={e.description}/>)
            }
        </div>
      </div>
      </div>
      <div className={styles.container}>
      <div className={styles.staffContainer}>
        <div className={styles.servicesTitle}>
          <h1>Nuestro Staff</h1>
          <h3>
          Le brindamos un servicio profesional a un precio insuperable para que usted solo se concentre en su negocio
          </h3>
        </div>
        <Cards />
      </div>
      </div>
    </>
  );
}
