import Head from "next/head";
import Image from "next/image";
import aboutPic from "@/image/genteTrabajando.png";
import styles from "@/modules/index.module.css";
import AdsClickIcon from "@mui/icons-material/AdsClick";
import Cards from "@/componentes/staffCard";

const services = [
  {
    icon: <AdsClickIcon />,
    title: "Shooting Stars",
    description:
      "Fingerstache flexitarian street art 8-bit waist co, subway tile poke farm.",
  },
  {
    icon: <AdsClickIcon />,
    title: "Camaras de seguridad",
    description:
      "Proveemos equipamiento para que su empresa esté protegida las 24 hs.",
  },
  {
    icon: <AdsClickIcon />,
    title: "Soporte de Computadoras",
    description:
      "Soporte informático para sus computadoras y servidores.",
  },
  {
    icon: <AdsClickIcon />,
    title: "Atención Inmediata",
    description:
      "Contamos con atención telefónica, Whatsapp y mail.",
  },
  {
    icon: <AdsClickIcon />,
    title: "Optimización de equipos",
    description:
      "Soluciones informáticas contempla todos los aspectos de su equipo. Ya sea software, hardware, o redes, trabajos para prevenir y solucionar todos sus problemas informáticos.",
  },
  {
    icon: <AdsClickIcon />,
    title: "Shooting Stars",
    description:
      "Fingerstache flexitarian street art 8-bit waist co, subway tile poke farm.",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Kraken Soluciones</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.heroContainer}></div>
      <div className={styles.container}>
        <div className={styles.aboutContainer}>
          {/* <div>
            <Image
              src={aboutPic}
              width={450}
              height={300}
              alt="Picture of About"
            />
          </div> */}
          <div className={styles.aboutText}>
            <h1 className={styles.title}>Nuestra Filosofía</h1>
            <div className={styles.aboutParagraph}>
            <p>
              Kraken nació como un grupo de amigos con una misión en mente: poder solucionar los
              problemas de sus computadoras antes que sucedan, y llevar a las compañias y emprendendores a que tengan una presencia en el mundo virtual.
            </p>
            <p>
              Nuestro compromiso es ayudarlo a potenciar el rendimiento y la
              calidad de los servidores a través de un mantenimiento informático
              que sea responsable, previsor y confiable.
            </p>
            <p>
              Y crear las herramientas informaticas necesarias para cumplir sus objetivos.
            </p>
            </div>
          </div>
        </div>
      </div>
      <div className={styles.container}>
        <div className={styles.servicesTitle}>
          <h1  className={styles.servicesTitle}>Nuestros Servicios</h1>
          <h3>
          Podemos brindarle una solución integral de mantenimiento a través de planes de abonos personalizados.
          </h3>
        </div>
        <div className={styles.servicesCardContainer}>
          {services &&
            services.map((s) => (
              <div className={styles.servicesCard}>
                {s.icon}
                <h3>{s.title}</h3>
                <p>{s.description}</p>
              </div>
            ))}
        </div>
      </div>
      <div className={styles.container}>
        <div className={styles.servicesTitle}>
          <h1>Nuestro Staff</h1>
          <h3>
          Le brindamos un servicio profesional a un precio insuperable para que usted solo se concentre en su negocio
          </h3>
        </div>
        <Cards />
      </div>
    </>
  );
}
