import Head from "next/head";
import styles from "@/modules/index.module.css";
import AdsClickIcon from "@mui/icons-material/AdsClick";
import Cards from "@/componentes/staffCard";

const services = [
  {
    icon: <AdsClickIcon />,
    title: "Shooting Stars",
    description:
      "Fingerstache flexitarian street art 8-bit waist co, subway tile poke farm.",
  },
  {
    icon: <AdsClickIcon />,
    title: "Camaras de seguridad",
    description:
      "Proveemos equipamiento para que su empresa esté protegida las 24 hs.",
  },
  {
    icon: <AdsClickIcon />,
    title: "Soporte de Computadoras",
    description:
      "Soporte informático para sus computadoras y servidores.",
  },
  {
    icon: <AdsClickIcon />,
    title: "Atención Inmediata",
    description:
      "Contamos con atención telefónica, Whatsapp y mail.",
  },
  {
    icon: <AdsClickIcon />,
    title: "Optimización de equipos",
    description:
      "Soluciones informáticas contempla todos los aspectos de su equipo. Ya sea software, hardware, o redes, trabajos para prevenir y solucionar todos sus problemas informáticos.",
  },
  {
    icon: <AdsClickIcon />,
    title: "Shooting Stars",
    description:
      "Fingerstache flexitarian street art 8-bit waist co, subway tile poke farm.",
  },
];

export default function Home() {
  return (
    <>
      <Head>
        <title>Kraken Soluciones</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.heroContainer}></div>
      <div className={styles.container}>
        <div className={styles.aboutContainer}>
          {/* <div>
            <Image
              src={aboutPic}
              width={450}
              height={300}
              alt="Picture of About"
            />
          </div> */}
          <div className={styles.aboutText}>
            <h1 className={styles.title}>Nuestra Filosofía</h1>
            <div className={styles.aboutParagraph}>
            <p>
            Bienvenido a Kraken, donde la tecnología se encuentra con la innovación para llevar su negocio al siguiente nivel. Conformado por un equipo de tres amigos apasionados por la excelencia en sus respectivas áreas, Kraken se destaca por su enfoque integral y su compromiso inquebrantable con la satisfacción del cliente.
            </p>
            <p>
            Desde nuestro inicio, nos hemos dedicado a una misión clara: anticipar y resolver los problemas informáticos antes de que surjan, permitiendo así que empresas y emprendedores puedan destacarse en el vasto mundo virtual.
            </p>
            <p>
            Nuestro equipo está compuesto por expertos en diferentes campos: un fullstack developer con amplia experiencia en el desarrollo de soluciones digitales innovadoras, un estratega de marketing con visión estratégica y creatividad sin límites, y un especialista en servidores y seguridad web que garantiza la integridad y protección de sus datos.
            </p>
            <p>
            En Kraken, no solo ofrecemos servicios, sino que forjamos asociaciones sólidas basadas en la confianza mutua y el compromiso compartido con la excelencia. Permítanos ser su socio tecnológico confiable mientras navega por las aguas del mundo digital. Juntos, podemos hacer que su visión se convierta en realidad.
            </p>
            <p>
            Descubra cómo podemos transformar su negocio hoy mismo con Kraken.
            </p>
            </div>
          </div>
        </div>
      </div>
      <div className={styles.container}>
      <div className={styles.serviceContainer}> 
        <div className={styles.servicesTitle}>
          <h1  className={styles.servicesTitle}>Nuestros Servicios</h1>
          <h3>
          Podemos brindarle una solución integral de mantenimiento a través de planes de abonos personalizados.
          </h3>
        </div>
        <div className={styles.servicesCardContainer}>
          {services &&
            services.map((s) => (
              <div className={styles.servicesCard}>
                {s.icon}
                <h3>{s.title}</h3>
                <p>{s.description}</p>
              </div>
            ))}
        </div>
      </div>
      </div>
      <div className={styles.container}>
      <div className={styles.staffContainer}>
        <div className={styles.servicesTitle}>
          <h1>Nuestro Staff</h1>
          <h3>
          Le brindamos un servicio profesional a un precio insuperable para que usted solo se concentre en su negocio
          </h3>
        </div>
        <Cards />
      </div>
      </div>
    </>
  );
}
